### ISSUE TITLE
Use Maven Wrapper for building trevas-jupyter

### ISSUE THREAD

**Issue by jornfranke** [InseeFrLab/Trevas-Jupyter#109]
Maven wrapper ensures that developer and CI pipeline use always the same version of the Maven build tool. This is useful to make the build reproducible. 

You can find more information here:
https://maven.apache.org/wrapper/

To configure the Maven project with Maven wrapper initialize once for the project
```
mvn wrapper:wrapper
```
Commit all files that the command creates.

Afterwards each developer can simply use the mvnw, e.g.
```mvnw package```

It will check if Maven is installed, if not then it will fetch it and provide the specified version in the wrapper conf file. If it is then available it will run simply maven with the parameter specified (in the example: package)

**Comment by NicoLaval** [comment]
Good idea.

Could you submit a PR?

**Comment by NicoLaval** [comment]
Fix 936295c555608cc0241a40cc6cfe9521c3296063
